import React, { useState, useEffect } from 'react';
import { jsPDF } from "jspdf";
import { analyzeConjunction } from '../services/api';
import './ConjunctionPanel.css';

// ==================== PDF Generator ====================
const generatePDF = (result, satA, satB) => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header band
  const headerHeight = 50;
  doc.setFillColor('#172635'); // Deep Navy
  doc.rect(0, 0, pageWidth, headerHeight, 'F');
  doc.setTextColor('#FFFFFF');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('DEBRISNET', margin, 30);
  doc.setFontSize(12);
  doc.text('ORBITAL CONJUNCTION FORECAST', margin + 120, 30);
  doc.text('Space Situational Awareness Division', margin, 45);
  doc.setFontSize(10);
  doc.text('Report Classification: MISSION ANALYSIS DOCUMENT', margin, 60);
  y = headerHeight + 20;

  // Helper to draw a boxed section
  const drawSection = (title, entries) => {
    const boxHeight = 40 + entries.length * 15;
    doc.setFillColor('#F4F1E8'); // Paper surface
    doc.rect(margin - 10, y - 10, contentWidth + 20, boxHeight, 'F');
    doc.setDrawColor('#C8C3B6'); // Technical border
    doc.rect(margin - 10, y - 10, contentWidth + 20, boxHeight);
    doc.setTextColor('#172635');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(title, margin, y);
    let lineY = y + 20;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    entries.forEach(entry => {
      doc.text(`${entry.key}: ${entry.value}`, margin, lineY);
      lineY += 15;
    });
    y = lineY + 10;
  };

  // Mission Details
  drawSection('MISSION DETAILS', [
    { key: 'Report ID', value: `DBN-${Date.now()}` },
    { key: 'Generated Time', value: new Date().toUTCString() },
    { key: 'Analysis Model', value: 'SGP4 Future Forecasting' },
    { key: 'Prediction Window', value: `${result.prediction_window_hours} HOURS` },
  ]);

  // Object Pair
  drawSection('OBJECT PAIR', [
    { key: 'Primary Object NORAD ID', value: satA },
    { key: 'Secondary Object NORAD ID', value: satB },
  ]);

  // Approach Analysis
  drawSection('APPROACH ANALYSIS', [
    { key: 'Analysis Start (UTC)', value: result.analysis_start || 'N/A' },
    { key: 'Analysis End (UTC)', value: result.analysis_end || 'N/A' },
    { key: 'Closest Approach Time (UTC)', value: result.closest_approach_time || 'N/A' },
    { key: 'Time Until Encounter', value: result.time_until_closest_approach || 'N/A' },
    { key: 'Minimum Separation', value: result.minimum_distance_km != null ? `${Number(result.minimum_distance_km).toFixed(3)} km` : 'N/A' },
    { key: 'Risk Status', value: result.risk_level?.toUpperCase() || 'N/A' },
  ]);

  // Command Decision
  drawSection('COMMAND DECISION', [
    { key: 'Autonomous Recommendation', value: result.recommendation || 'N/A' },
  ]);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor('#777777');
  doc.text('Generated by DebrisNet – AI Assisted Orbital Intelligence Platform', margin, pageHeight - 30);

  doc.save(`Conjunction_Forecast_${satA}_${satB}.pdf`);
};

const ConjunctionPanel = () => {
  const [satA, setSatA] = useState('');
  const [satB, setSatB] = useState('');
  const [predictionHours, setPredictionHours] = useState('24');
  const [customHours, setCustomHours] = useState('');
  
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const loadingMessages = [
    "✓ Loading orbital elements",
    "✓ Propagating trajectories",
    "✓ Computing miss distance",
    "✓ Generating mission assessment"
  ];
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);

  // Loading ticker effect
  useEffect(() => {
    if (!loading) return;
    const interval = setInterval(() => {
      setLoadingStep(prev => (prev + 1) % loadingMessages.length);
    }, 1500);
    return () => clearInterval(interval);
  }, [loading]);

  const validateId = id => /^\d+$/.test(id) && id.length <= 6;

  const getHours = () => predictionHours === 'Custom' ? Number(customHours) : Number(predictionHours);

  const handleAnalyze = async () => {
    if (!validateId(satA) || !validateId(satB)) {
      setError('Enter valid NORAD IDs (numeric, ≤6 digits).');
      return;
    }
    const hours = getHours();
    if (isNaN(hours) || hours <= 0) {
      setError('Enter a valid prediction window in hours.');
      return;
    }
    setError(null);
    setLoading(true);
    setResult(null);
    try {
      const data = await analyzeConjunction(satA, satB, hours);
      if (!data || data.minimum_distance_km == null) {
        setError('No conjunction data returned.');
      } else {
        setResult(data);
      }
    } catch (e) {
      setError('Backend unavailable or request failed');
    } finally {
      setLoading(false);
    }
  };

  const handleExport = () => {
    if (result) generatePDF(result, satA, satB);
  };

  // Helper to format ISO time to mission format
  const formatMissionTime = (isoString) => {
    if (!isoString) return 'N/A';
    try {
      const date = new Date(isoString);
      const dd = String(date.getUTCDate()).padStart(2, '0');
      const mm = String(date.getUTCMonth() + 1).padStart(2, '0');
      const yyyy = date.getUTCFullYear();
      const hh = String(date.getUTCHours()).padStart(2, '0');
      const min = String(date.getUTCMinutes()).padStart(2, '0');
      return `${dd}-${mm}-${yyyy} AT ${hh}:${min} UTC`;
    } catch (e) {
      return isoString;
    }
  };

  return (
    <div className="conjunction-panel">
      <h2 className="panel-title">CONJUNCTION INTELLIGENCE CENTER</h2>

      {/* OBJECT PAIR CONFIGURATION & PREDICTION WINDOW */}
      <div className="inputs" style={{ display: 'flex', flexDirection: 'row', gap: '1rem', alignItems: 'flex-start', flexWrap: 'wrap' }}>
        <div className="object-section primary" style={{ flex: '1 1 200px' }}>
          <span className="object-label" style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#777777', marginBottom: '0.25rem' }}>PRIMARY OBJECT</span>
          <input
            type="text"
            placeholder="NORAD ID"
            value={satA}
            onChange={e => setSatA(e.target.value)}
            className="object-input"
          />
        </div>
        <div className="object-section secondary" style={{ flex: '1 1 200px' }}>
          <span className="object-label" style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#777777', marginBottom: '0.25rem' }}>SECONDARY OBJECT</span>
          <input
            type="text"
            placeholder="NORAD ID"
            value={satB}
            onChange={e => setSatB(e.target.value)}
            className="object-input"
          />
        </div>
        <div className="object-section prediction" style={{ flex: '1 1 200px' }}>
          <span className="object-label" style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#777777', marginBottom: '0.25rem' }}>PREDICTION WINDOW</span>
          <select 
            value={predictionHours} 
            onChange={e => setPredictionHours(e.target.value)}
            className="object-input"
            style={{ width: '100%', padding: '0.55rem 0.75rem', border: '1.5px solid #A8ADA3', borderRadius: '2px', fontFamily: 'var(--font-mono)', fontSize: '0.9rem', color: '#111827', background: '#FFFFFF' }}
          >
            <option value="1">1 HOUR</option>
            <option value="6">6 HOURS</option>
            <option value="12">12 HOURS</option>
            <option value="24">24 HOURS</option>
            <option value="72">72 HOURS</option>
            <option value="Custom">CUSTOM</option>
          </select>
          {predictionHours === 'Custom' && (
            <input 
              type="number"
              placeholder="CUSTOM WINDOW (HOURS)"
              value={customHours}
              onChange={e => setCustomHours(e.target.value)}
              className="object-input"
              style={{ marginTop: '0.5rem' }}
            />
          )}
        </div>
      </div>

      {/* Run Analysis Button */}
      <button
        className="analyze-btn"
        onClick={handleAnalyze}
        disabled={loading}
        style={{ marginTop: '0.5rem', width: '100%', padding: '0.75rem', fontSize: '1rem' }}
      >
        {loading ? 'ANALYZING ORBITS...' : 'RUN CONJUNCTION ANALYSIS'}
      </button>

      {/* Empty idle state */}
      {!loading && !result && !error && (
        <p className="empty-state" style={{ marginTop: '2rem', textAlign: 'center', color: '#777777' }}>
          <strong>CONJUNCTION SYSTEM IDLE</strong><br/>Awaiting primary and secondary orbital objects.
        </p>
      )}

      {/* Loading state */}
      {loading && (
        <div className="calc-loading" style={{ marginTop: '2rem' }}>
          <p className="calc-title" style={{ fontWeight: 'bold' }}>CALCULATING CLOSE APPROACH EVENT</p>
          <ul className="calc-steps" style={{ listStyle: 'none', padding: 0 }}>
            {loadingMessages.map((msg, idx) => (
              <li key={idx} style={{ color: idx <= loadingStep ? '#C76D32' : '#C8C3B6', margin: '0.25rem 0' }}>{msg}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Error */}
      {error && <p className="error-msg" style={{ marginTop: '2rem', textAlign: 'center' }}>{error}</p>}

      {/* Result */}
      {result && (
        <div className="result-section" style={{ marginTop: '2rem' }}>
          
          {/* Approach Geometry Grid */}
          <div className="card" style={{ padding: '1.5rem', borderLeft: '4px solid #172635' }}>
            <h3 style={{ color: '#172635', marginBottom: '1.5rem', fontSize: '1rem', letterSpacing: '0.05em' }}>APPROACH GEOMETRY</h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem' }}>
              <div>
                <span style={{color:'#777777', fontSize: '0.75rem', fontWeight: 'bold', display: 'block', marginBottom: '0.25rem'}}>PREDICTION WINDOW</span>
                <strong style={{color:'#172635', fontSize: '1.1rem'}}>{result.prediction_window_hours} HOURS</strong>
              </div>
              <div style={{ gridColumn: '1 / -1' }}>
                <span style={{color:'#777777', fontSize: '0.75rem', fontWeight: 'bold', display: 'block', marginBottom: '0.25rem'}}>ANALYSIS PERIOD</span>
                <strong style={{color:'#172635', fontSize: '1.1rem'}}>FROM {formatMissionTime(result.analysis_start)}</strong>
                <span style={{color:'#C76D32', margin: '0 0.5rem'}}>→</span>
                <strong style={{color:'#172635', fontSize: '1.1rem'}}>TO {formatMissionTime(result.analysis_end)}</strong>
              </div>
              <div>
                <span style={{color:'#777777', fontSize: '0.75rem', fontWeight: 'bold', display: 'block', marginBottom: '0.25rem'}}>CLOSEST APPROACH</span>
                <strong style={{color:'#172635', fontSize: '1.1rem'}}>{formatMissionTime(result.closest_approach_time)}</strong>
              </div>
              <div>
                <span style={{color:'#777777', fontSize: '0.75rem', fontWeight: 'bold', display: 'block', marginBottom: '0.25rem'}}>TIME UNTIL ENCOUNTER</span>
                <strong style={{color:'#172635', fontSize: '1.1rem'}}>{result.time_until_closest_approach.toUpperCase()}</strong>
              </div>
              <div>
                <span style={{color:'#777777', fontSize: '0.75rem', fontWeight: 'bold', display: 'block', marginBottom: '0.25rem'}}>MINIMUM SEPARATION</span>
                <strong style={{color:'#172635', fontSize: '1.1rem'}}>{result.minimum_distance_km != null ? `${Number(result.minimum_distance_km).toFixed(2)} KM` : 'N/A'}</strong>
              </div>
            </div>
          </div>

          {/* Collision Risk Classification */}
          <div className="card" style={{ marginTop: '1.5rem', padding: '1.5rem' }}>
            <h3 style={{ color: '#172635', marginBottom: '1rem', fontSize: '1rem', letterSpacing: '0.05em' }}>COLLISION RISK CLASSIFICATION</h3>
            <div style={{ display: 'flex', gap: '2rem', alignItems: 'center', flexWrap: 'wrap' }}>
              {['LOW', 'MEDIUM', 'HIGH'].map(level => {
                const isActive = result.risk_level?.toUpperCase() === level;
                let activeColor = '#C76D32'; // Default orange accent
                if (level === 'HIGH') activeColor = '#A94438'; // Red only if HIGH
                if (level === 'LOW') activeColor = '#172635'; // Dark navy for LOW
                return (
                  <div key={level} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', opacity: isActive ? 1 : 0.4 }}>
                    <span style={{ fontSize: '1.5rem', color: isActive ? activeColor : '#C8C3B6' }}>
                      {isActive ? '●' : '○'}
                    </span>
                    <strong style={{ color: isActive ? activeColor : '#777777', fontSize: '1.1rem' }}>{level}</strong>
                  </div>
                );
              })}
            </div>
          </div>
          
          {/* Autonomous Recommendation */}
          <div className="card" style={{ marginTop: '1.5rem', padding: '1.5rem', borderLeft: '4px solid #C76D32' }}>
            <h3 style={{ color: '#C76D32', marginBottom: '0.5rem', fontSize: '1rem', letterSpacing: '0.05em' }}>AUTONOMOUS RECOMMENDATION</h3>
            <p style={{ color: '#172635', fontSize: '1.1rem', margin: 0, fontWeight: '500' }}>{result.recommendation}</p>
          </div>

          {/* Export button */}
          <button className="export-btn" onClick={handleExport} style={{marginTop: '2rem', width: '100%'}}>
            EXPORT MISSION REPORT
          </button>
        </div>
      )}
    </div>
  );
};

export default ConjunctionPanel;
