import React, { useState, useEffect } from 'react';
import { jsPDF } from "jspdf";
import { analyzeConjunction } from '../services/api';
import './ConjunctionPanel.css';

// ==================== PDF Generator (unchanged) ====================
const generatePDF = (result, satA, satB) => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header band
  const headerHeight = 50;
  doc.setFillColor('#172635'); // Deep Navy
  doc.rect(0, 0, pageWidth, headerHeight, 'F');
  doc.setTextColor('#FFFFFF');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('DEBRISNET', margin, 30);
  doc.setFontSize(12);
  doc.text('ORBITAL CONJUNCTION ASSESSMENT', margin + 120, 30);
  doc.text('Space Situational Awareness Division', margin, 45);
  doc.setFontSize(10);
  doc.text('Report Classification: MISSION ANALYSIS DOCUMENT', margin, 60);
  y = headerHeight + 20;

  // Helper to draw a boxed section
  const drawSection = (title, entries) => {
    const boxHeight = 40 + entries.length * 15;
    doc.setFillColor('#F4F1E8'); // Paper surface
    doc.rect(margin - 10, y - 10, contentWidth + 20, boxHeight, 'F');
    doc.setDrawColor('#C8C3B6'); // Technical border
    doc.rect(margin - 10, y - 10, contentWidth + 20, boxHeight);
    doc.setTextColor('#172635');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(title, margin, y);
    let lineY = y + 20;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    entries.forEach(entry => {
      doc.text(`${entry.key}: ${entry.value}`, margin, lineY);
      lineY += 15;
    });
    y = lineY + 10;
  };

  // Mission Details
  drawSection('MISSION DETAILS', [
    { key: 'Report ID', value: `DBN-${Date.now()}` },
    { key: 'Generated Time', value: new Date().toUTCString() },
    { key: 'Analysis Model', value: 'SGP4' },
    { key: 'Data Source', value: 'Live TLE' },
  ]);

  // Object Pair
  drawSection('OBJECT PAIR', [
    { key: 'Primary Object NORAD ID', value: satA },
    { key: 'Secondary Object NORAD ID', value: satB },
  ]);

  // Approach Analysis
  drawSection('APPROACH ANALYSIS', [
    { key: 'Closest Approach Distance', value: result.closest_approach?.distance_km != null ? `${Number(result.closest_approach.distance_km).toFixed(3)} km` : 'N/A' },
    { key: 'Risk Status', value: result.risk_assessment?.risk_level?.toUpperCase() || 'N/A' },
  ]);

  // Mission Intelligence Summary
  const intelStartY = y;
  const intelBoxHeight = 100;
  doc.setFillColor('#F4F1E8');
  doc.rect(margin - 10, intelStartY - 10, contentWidth + 20, intelBoxHeight, 'F');
  doc.setDrawColor('#C8C3B6');
  doc.rect(margin - 10, intelStartY - 10, contentWidth + 20, intelBoxHeight);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor('#172635');
  doc.text('MISSION INTELLIGENCE', margin, intelStartY);
  const findings = [
    `Closest Separation: ${result.closest_approach?.distance_km != null ? `${Number(result.closest_approach.distance_km).toFixed(3)} km` : 'N/A'}`,
    `Collision Probability: ${result.risk_assessment?.risk_level?.toUpperCase() || 'N/A'}`,
    `Trajectory: ${result.ai_analysis?.analysis || 'N/A'}`,
    `Safety Margin: ${result.risk_assessment?.recommendation || 'N/A'}`,
  ];
  let fY = intelStartY + 20;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  findings.forEach(f => {
    doc.text(`✓ ${f}`, margin, fY);
    fY += 15;
  });
  y = fY + 10;

  // Command Decision
  drawSection('COMMAND DECISION', [
    { key: 'Action', value: result.risk_assessment?.recommendation || 'N/A' },
    { key: 'Reason', value: result.risk_assessment?.recommendation || 'N/A' },
  ]);

  // Avoidance Review (if present)
  if (result.avoidance_plan) {
    drawSection('AVOIDANCE REVIEW', [
      { key: 'Maneuver', value: result.avoidance_plan?.maneuver_required ? 'REQUIRED' : 'NOT REQUIRED' },
      { key: 'Delta‑V', value: `${result.avoidance_plan?.estimated_delta_v || '0'} m/s` },
      { key: 'Priority', value: result.avoidance_plan?.priority || 'LOW' },
    ]);
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor('#777777');
  doc.text('Generated by DebrisNet – AI Assisted Orbital Intelligence Platform', margin, pageHeight - 30);

  doc.save(`Conjunction_Report_${satA}_${satB}.pdf`);
};

// Helper to convert hex colour to RGB for jsPDF
const hexToRgb = hex => {
  const clean = hex.replace(/^#/, "");
  const bigint = parseInt(clean, 16);
  return [(bigint >> 16) & 255, (bigint >> 8) & 255, bigint & 255];
};

// Risk colour map for UI badge
const riskColorMap = {
  safe: '#15803D',
  watch: '#D97706',
  warning: '#B45309',
  critical: '#B91C1C'
};
const getRiskColor = level => riskColorMap[(level || '').toLowerCase()] || '#777';

const ConjunctionPanel = () => {
  const [satA, setSatA] = useState('');
  const [satB, setSatB] = useState('');
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const loadingMessages = [
    "✓ Loading orbital elements",
    "✓ Propagating trajectories",
    "✓ Computing miss distance",
    "✓ Generating mission assessment"
  ];
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);

  // Loading ticker effect
  useEffect(() => {
    if (!loading) return;
    const interval = setInterval(() => {
      setLoadingStep(prev => (prev + 1) % loadingMessages.length);
    }, 1500);
    return () => clearInterval(interval);
  }, [loading]);

  const validateId = id => /^\d+$/.test(id) && id.length <= 6;

  const handleAnalyze = async () => {
    if (!validateId(satA) || !validateId(satB)) {
      setError('Enter valid NORAD IDs (numeric, ≤6 digits).');
      return;
    }
    setError(null);
    setLoading(true);
    setResult(null);
    try {
      const data = await analyzeConjunction(satA, satB);
      if (!data || !data.closest_approach) {
        setError('No conjunction data returned.');
      } else {
        setResult(data);
      }
    } catch (e) {
      setError('Backend unavailable or request failed');
    } finally {
      setLoading(false);
    }
  };

  const handleExport = () => {
    if (result) generatePDF(result, satA, satB);
  };

  return (
    <div className="conjunction-panel">
      <h2 className="panel-title">CONJUNCTION INTELLIGENCE CENTER</h2>

      {/* OBJECT PAIR CONFIGURATION */}
      <div className="object-pair">
        <div className="object-section primary">
          <span className="object-label">PRIMARY OBJECT</span>
          <input
            type="text"
            placeholder="NORAD ID"
            value={satA}
            onChange={e => setSatA(e.target.value)}
            className="object-input"
          />
          <span className="object-status">READY</span>
        </div>
        <div className="middle-indicator">
          <span className="screening-label">CONJUNCTION SCREENING</span>
          <span className="model-label">MODEL: SGP4</span>
        </div>
        <div className="object-section secondary">
          <span className="object-label">SECONDARY OBJECT</span>
          <input
            type="text"
            placeholder="NORAD ID"
            value={satB}
            onChange={e => setSatB(e.target.value)}
            className="object-input"
          />
          <span className="object-status">READY</span>
        </div>
      </div>
      {/* Run Analysis Button */}
      <button
        className="analyze-btn"
        onClick={handleAnalyze}
        disabled={loading}
      >
        {loading ? 'ANALYZING ORBITS...' : 'RUN CONJUNCTION ANALYSIS'}
      </button>

      {/* Empty idle state */}
      {!loading && !result && !error && (
        <p className="empty-state">CONJUNCTION SYSTEM IDLE<br/>Awaiting primary and secondary orbital objects.</p>
      )}

      {/* Loading state */}
      {loading && (
        <div className="calc-loading">
          <p className="calc-title">CALCULATING CLOSE APPROACH EVENT</p>
          <ul className="calc-steps">
            {loadingMessages.map((msg, idx) => (
              <li key={idx} className={idx <= loadingStep ? 'step-done' : ''}>{msg}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Error */}
      {error && <p className="error-msg">{error}</p>}

      {/* Result */}
      {result && (
        <div className="result-section">
          {/* Approach Geometry */}
          <div className="section-box">
            <h3 className="section-header">APPROACH GEOMETRY</h3>
            <p><strong>Closest Approach Distance:</strong> {result.closest_approach?.distance_km != null ? `${Number(result.closest_approach.distance_km).toFixed(2)} km` : 'N/A'}</p>
            <p><strong>Time of Closest Approach:</strong> {result.closest_approach?.time || 'N/A'}</p>
            <p><strong>Analysis Timestamp:</strong> {new Date().toISOString()}</p>
          </div>

          {/* Collision Risk Classification */}
          <div className="card risk-card">
            <h3 className="card-title">COLLISION RISK CLASSIFICATION</h3>
            <div className="risk-bar">
              <span className="risk-label">SAFE</span>
              <span className={`risk-level ${result.risk_assessment?.risk_level?.toLowerCase() === 'safe' ? 'active' : ''}`}></span>
            </div>
            <div className="risk-bar">
              <span className="risk-label">WATCH</span>
              <span className={`risk-level ${result.risk_assessment?.risk_level?.toLowerCase() === 'watch' ? 'active' : ''}`}></span>
            </div>
            <div className="risk-bar">
              <span className="risk-label">WARNING</span>
              <span className={`risk-level ${result.risk_assessment?.risk_level?.toLowerCase() === 'warning' ? 'active' : ''}`}></span>
            </div>
            <div className="risk-bar">
              <span className="risk-label">CRITICAL</span>
              <span className={`risk-level ${result.risk_assessment?.risk_level?.toLowerCase() === 'critical' ? 'active' : ''}`}></span>
            </div>
          </div>
          <div className="card risk-status-card">
            <h3 className="card-title">OVERALL RISK STATUS</h3>
            <div className={`badge large-badge badge-${result.risk_assessment?.risk_level?.toLowerCase() || 'unknown'}`}>{result.risk_assessment?.risk_level?.toUpperCase() || 'N/A'}</div>
          </div>

          {/* Key Findings */}
          <div className="key-findings-grid">
            <div className="card key-card">
              <h4 className="card-subtitle">CLOSEST APPROACH</h4>
              <p className="key-value">{result.closest_approach?.distance_km != null ? `${Number(result.closest_approach.distance_km).toFixed(3)} km` : 'N/A'}</p>
              <p className="key-label">ACCEPTABLE</p>
            </div>
            <div className="card key-card">
              <h4 className="card-subtitle">COLLISION RISK</h4>
              <p className="key-value">{result.risk_assessment?.risk_level?.toUpperCase() || 'N/A'}</p>
              <p className="key-label">BELOW THRESHOLD</p>
            </div>
            <div className="card key-card">
              <h4 className="card-subtitle">TRAJECTORY STATUS</h4>
              <p className="key-value">{result.ai_analysis?.analysis || 'N/A'}</p>
              <p className="key-label">CLEAR</p>
            </div>
          </div>

          {/* Maneuver Status */}
          <div className="card maneuver-status-card">
            <h3 className="card-title">MANEUVER STATUS</h3>
            <div className={`badge large-badge badge-${result.avoidance_plan?.maneuver_required ? 'critical' : 'success'}`}>{result.avoidance_plan?.maneuver_required ? 'MANEUVER REQUIRED' : 'MANEUVER NOT REQUIRED'}</div>
            {!result.avoidance_plan?.maneuver_required && <div className="badge approval-badge">✓ APPROVED</div>}
          </div>
          <div className="dynamics-subcards">
            <div className="card small-card">
              <h4 className="card-subtitle">DELTA‑V BUDGET</h4>
              <p>{result.avoidance_plan?.estimated_delta_v ?? '0'} m/s</p>
            </div>
            <div className="card small-card">
              <h4 className="card-subtitle">PRIORITY</h4>
              <p>{result.avoidance_plan?.priority ?? 'LOW'}</p>
            </div>
            <div className="card small-card">
              <h4 className="card-subtitle">MISSION COMMAND</h4>
              <p>{result.avoidance_plan?.recommended_action ?? 'Maintain current orbit'}</p>
            </div>
          </div>

          {/* Export button */}
          <button className="export-btn" onClick={handleExport}>EXPORT MISSION REPORT</button>
        </div>
      )}
    </div>
  );
};

export default ConjunctionPanel;
